"""empty message

Revision ID: 70ab4f174f48
Revises: 8cde3ff867b7
Create Date: 2024-12-15 14:55:44.077255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ab4f174f48'
down_revision = '8cde3ff867b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=225),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=225),
               existing_nullable=False)

    with op.batch_alter_table('scraped_data', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=225),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('public_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('team_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=225),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('public_id',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('scraped_data', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('team_id',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
